"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const errorHandler_1 = require("./middleware/errorHandler");
const createError = require("http-errors");
const path = require("path");
const express = require("express");
const cookieParser = require("cookie-parser");
const logger = require("morgan");
const dotenv = require("dotenv");
dotenv.config();
const indexRouter = require("./routes/index");
const usersRouter = require("./routes/users");
const app = express();
// view engine setup
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "jade");
app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "public")));
app.use("/devbank", indexRouter);
app.use("/devbank-user", usersRouter);
app.all("*", errorHandler_1.unavailableRoutes);
module.exports = app;
