"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const users_controller_1 = require("../controllers/users.controller");
const tokenAuth_1 = require("../middleware/tokenAuth");
const users_middleware_1 = require("../middleware/users.middleware");
const express = require("express");
const router = express.Router();
router.post("/logout", users_controller_1.userLogout);
router.post("/login", users_middleware_1.validateLogin, users_controller_1.userLogin);
router.post("/create-account", tokenAuth_1.validateToken, users_controller_1.createAccountNumber);
router.post('/forgot-password');
module.exports = router;
